# stage 1
# FROM node:latest as build-stage
# WORKDIR /app
# COPY package*.json /app/
# RUN npm install
# COPY ./ /app/
# RUN npm run build --prod

# stage 2
# stable nginx version
FROM nginx:latest
# COPY --from=build-stage /app/dist/cemsview /usr/share/nginx/html
COPY /dist/cemsview /usr/share/nginx/html
#Copy default nginx configuration
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

# docker build --pull --rm -f "DockerFile" -t test/frontend:v1 "."
# docker tag nathanrs15/monolithicbackend:latest registry.digitalocean.com/innsmouth/cemsview-auth:latest
# docker push registry.digitalocean.com/innsmouth/cemsview-auth:latest
# kubectl rollout restart deployment/cemsview-auth -n tersa
